import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: corsHeaders });

    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    // Verify the user JWT
    const { data: { user }, error: authError } = await createClient(
      SUPABASE_URL,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } }
    ).auth.getUser();

    if (authError || !user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: corsHeaders });
    }

    const { action, token } = await req.json();

    // ── DISCONNECT ──────────────────────────────────────────────────────────
    if (action === "disconnect") {
      // Get existing token to call deleteWebhook
      const { data: existing } = await supabase
        .from("telegram_bots")
        .select("bot_token")
        .eq("user_id", user.id)
        .single();

      if (existing?.bot_token) {
        await fetch(`https://api.telegram.org/bot${existing.bot_token}/deleteWebhook`, { method: "POST" });
      }

      await supabase.from("telegram_bots").delete().eq("user_id", user.id);
      return new Response(JSON.stringify({ success: true }), { headers: corsHeaders });
    }

    // ── CONNECT ─────────────────────────────────────────────────────────────
    if (action === "connect") {
      if (!token || typeof token !== "string" || !token.match(/^\d+:[A-Za-z0-9_-]{35,}$/)) {
        return new Response(JSON.stringify({ error: "Invalid bot token format" }), { status: 400, headers: corsHeaders });
      }

      // 1. Validate token with Telegram
      const meRes = await fetch(`https://api.telegram.org/bot${token}/getMe`);
      const meData = await meRes.json();

      if (!meData.ok) {
        return new Response(
          JSON.stringify({ error: "Invalid bot token — Telegram rejected it. Check and try again." }),
          { status: 400, headers: corsHeaders }
        );
      }

      const { username: botUsername, first_name: botName } = meData.result;

      // 2. Register our webhook URL with this bot
      // Each workspace gets a unique webhook URL so we know which workspace to use
      const webhookUrl = `${SUPABASE_URL}/functions/v1/telegram-handler?uid=${user.id}`;
      const webhookRes = await fetch(`https://api.telegram.org/bot${token}/setWebhook`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          url: webhookUrl,
          allowed_updates: ["message"],
          drop_pending_updates: true,
        }),
      });
      const webhookData = await webhookRes.json();

      if (!webhookData.ok) {
        return new Response(
          JSON.stringify({ error: "Failed to register webhook with Telegram. Try again." }),
          { status: 500, headers: corsHeaders }
        );
      }

      // 3. Store in database (upsert) — tokens are auto-generated by DB default
      const { data: botRow, error: dbError } = await supabase.from("telegram_bots").upsert({
        user_id: user.id,
        bot_token: token,
        bot_username: botUsername,
        bot_name: botName,
        webhook_registered: true,
        updated_at: new Date().toISOString(),
      }, { onConflict: "user_id" }).select("manager_token, staff_token").single();

      if (dbError) throw dbError;

      // 4. Register command menu so staff see autocomplete when typing /
      await fetch(`https://api.telegram.org/bot${token}/setMyCommands`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          commands: [
            { command: "reconcile",  description: "Daily cash reconciliation" },
            { command: "handover",   description: "Shift handover log" },
            { command: "restock",    description: "Supplier outreach (manager)" },
            { command: "audit",      description: "Inventory audit (manager)" },
            { command: "assign",     description: "Task assignment (manager)" },
            { command: "escalate",   description: "Escalation router (manager)" },
            { command: "sop",        description: "SOP compliance check (manager)" },
            { command: "sopupdate",  description: "SOP update notifier (manager)" },
            { command: "help",       description: "Show available commands" },
            { command: "cancel",     description: "Cancel current workflow" },
          ],
        }),
      });

      return new Response(
        JSON.stringify({
          success: true,
          bot_username: botUsername,
          bot_name: botName,
          manager_token: botRow?.manager_token,
          staff_token: botRow?.staff_token,
        }),
        { headers: corsHeaders }
      );
    }

    // ── GET STATUS ───────────────────────────────────────────────────────────
    if (action === "status") {
      const { data } = await supabase
        .from("telegram_bots")
        .select("bot_username, bot_name, webhook_registered, manager_token, staff_token, handover_watcher_enabled, shift_end_time, created_at")
        .eq("user_id", user.id)
        .single();

      return new Response(JSON.stringify({ connected: !!data, ...data }), { headers: corsHeaders });
    }

    // ── UPDATE WATCHER SETTINGS ──────────────────────────────────────────────
    if (action === "update_watcher") {
      const { handover_watcher_enabled, shift_end_time } = await req.json().catch(() => ({}));
      await supabase
        .from("telegram_bots")
        .update({
          handover_watcher_enabled: !!handover_watcher_enabled,
          shift_end_time: shift_end_time || "18:00",
          updated_at: new Date().toISOString(),
        })
        .eq("user_id", user.id);
      return new Response(JSON.stringify({ success: true }), { headers: corsHeaders });
    }

    return new Response(JSON.stringify({ error: "Unknown action" }), { status: 400, headers: corsHeaders });

  } catch (err: any) {
    console.error("telegram-setup error:", err);
    return new Response(JSON.stringify({ error: err.message || "Internal error" }), {
      status: 500,
      headers: corsHeaders,
    });
  }
});
